name: Snake Animations
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: "0 16 * * *"
jobs:
  generate:
    name: Generate Animations
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake animations
        uses: Platane/snk/svg-only@v3.2.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/grid-snake.svg
            dist/grid-snake-dark.svg?palette=github-dark
            dist/grid-snake-light.svg?palette=github-light

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          path: dist

  deploy:
    name: Deploy to Pages
    if: github.event_name != 'pull_request' && github.ref_name == 'main'
    needs: generate
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      group: pages
      cancel-in-progress: false
    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v3.0.6

      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v2.0.4
